import 'bootstrap/dist/css/bootstrap.min.css'

import "./globals.css";
import "./responsive.css";
import Header from '../components/header/header';
import Footer from '../components/footer/footer';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
      <body >
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
